config/routes.rb
Rails.application.routes.draw do
  # get '/reviews'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = %w(chinese italian horse japanese french belgian)
  has_many :reviews, dependent: :destroy

  validates_presence_of :name, :address, :category, :phone_number

  validates_inclusion_of :category, in: CATEGORY
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  RATING = [1, 2, 3, 4, 5]

  validates_presence_of :content, :rating

  validates_inclusion_of :rating, in: RATING
  validates :rating, numericality: { only_integer: true, message: "debe ser un número entero" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurant = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurants_path
  end

  def show

  end

  def edit

  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
  @restaurant.destroy

  redirect_to restaurants_path, status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
  @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant
    @review.destroy
    redirect_to restaurant_path(@restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY, prompt: "Seleccionar opción" %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurant.each do |restaurant| %>
    <li><h3><%= restaurant.name %></h3> <p><%= link_to "See details", restaurant_path(restaurant) %></p></li>
  <% end %>
</ul>

<h4><%= link_to "new Restaurant", new_restaurant_path %></h4>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<ul>
  <li><%= @restaurant.address %></li>
  <li><%= @restaurant.phone_number %></li>
  <li><%= @restaurant.category %></li>
</ul>

<%= link_to "update", edit_restaurant_path %><br>
<%= link_to "back to restaurants", restaurants_path %><br>
<%= link_to "Delete restaurant",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

<%= link_to "New Review", new_restaurant_review_path(@restaurant) %>

<p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %> -- <%= review.rating %> </li>
    <li><%= link_to "Delete review", review_path(review) ,data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
  <% end %>
</ul>
<br>

app/views/reviews/new.html.erb
<div class="container">

  <h1>New Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: Review::RATING, prompt: "Seleccionar opción" %>
    <%= f.submit "Submit Review", class: "btn-btn-primary" %>
  <% end  %>

</div>